- id: '1583566484464'
  alias: Turn Lights on Evening
  description: Turn on Gate Lamp, 1st Flr Portico and Elevation Lamp
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.gate_lamp
    service: switch.turn_on
  - data:
      entity_id: switch.1st_portico
    service: switch.turn_on
  - data: {}
    entity_id: switch.elevation
    service: switch.turn_on
  - data: {}
    entity_id: switch.vinayagar
    service: switch.turn_on
- id: '1583600836399'
  alias: Turn-off all the lights
  trigger:
  - at: '6:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vinayagar
    service: switch.turn_off
  - data: {}
    entity_id: switch.gnd_lamp
    service: switch.turn_off
- id: '1585061076035'
  alias: Turn-off Elevation,Gate Lamp lights, On GND Lamp
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.gate_lamp
    service: switch.turn_off
  - data: {}
    entity_id: switch.elevation
    service: switch.turn_off
  - data: {}
    entity_id: switch.gnd_lamp
    service: switch.turn_on
- id: '1585302778929'
  alias: Turn Vinayagar,1st Portico Off at 22:00
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vinayagar
    service: switch.turn_off
  - data: {}
    entity_id: switch.1st_portico
    service: switch.turn_off
- id: '1586170890757'
  alias: Notify if Bore Tank Goes Empty
  description: Notify if Bore Tank Goes Empty
  trigger:
  - entity_id: switch.bore_tanks
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Tank will be Empty, On the
        Bore motor'
      title: BORE TANKS GOING TO BE EMPTY
    service: notify.mypushbullet
- id: '1586171756740'
  alias: Notify if Corp Tank Goes Empty
  description: ''
  trigger:
  - entity_id: switch.tank_1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Corp Tank will be Empty, On
        the Sump motor'
      title: CORP TANK GOING TO BE EMPTY
    service: notify.mypushbullet
- id: '1586171839711'
  alias: Notify if Corp Tank Gets Full
  description: ''
  trigger:
  - entity_id: switch.tank_1
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Tank Going be FULL, Off the
        Sump motor'
      title: CORP TANK GOING TO BE FULL
    service: notify.mypushbullet
- id: '1586171933447'
  alias: Notify if Bore Tanks Gets Full
  description: ''
  trigger:
  - entity_id: switch.bore_tanks
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Bore Tanks Going to be FULL,
        OFF the Bore motor'
      title: BORE TANKS GOING TO FULL
    service: notify.mypushbullet
- id: '1586927169512'
  alias: 'Switch ON Charger if Laptop battery goes Less than 20 % '
  description: ''
  trigger:
  - below: '20'
    entity_id: sensor.geek_laptop_battery
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.geek_charger
    service: switch.turn_on
- id: '1586927260164'
  alias: 'Switch OFF Charger if Laptop battery goes Greater than 95 % '
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.geek_laptop_battery
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.geek_charger
    service: switch.turn_off
