- id: '1583566484464'
  alias: Turn Lights on Evening
  description: Turn on Gate Lamp, 1st Flr Portico and Elevation Lamp
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.gate_lamp
    service: switch.turn_on
  - data:
      entity_id: switch.1st_portico
    service: switch.turn_on
  - data: {}
    entity_id: switch.elevation
    service: switch.turn_on
- id: '1583600836399'
  alias: Turn-off all the lights
  trigger:
  - at: '6:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vinayagar
    service: switch.turn_off
  - data: {}
    entity_id: switch.gnd_lamp
    service: switch.turn_off
- id: '1585061076035'
  alias: Turn-off specific lights on switch on others
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.1st_portico
    service: switch.turn_off
  - data: {}
    entity_id: switch.gate_lamp
    service: switch.turn_off
  - data: {}
    entity_id: switch.elevation
    service: switch.turn_off
  - data: {}
    entity_id: switch.gnd_lamp
    service: switch.turn_on
- id: '1585302778929'
  alias: Turn Vinayagar On at 7:00
  description: ''
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vinayagar
    service: switch.turn_on
