- id: '1569249614326'
  alias: If both sump and bore has water
  trigger:
  - entity_id: switch.over_tank_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.sump_tank_status
    state: 'off'
  action:
  - service: script.1569249552584
- id: '1569252667690'
  alias: If Sump Gets Empty Suddenly
  trigger:
  - entity_id: switch.sump_tank_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: script.1569249552584
    state: 'on'
  action:
  - data:
      entity_id: script.1569249552584
    service: script.turn_off
  - data:
      entity_id: switch.motor_sump
    service: switch.turn_off
  - delay: 00:01:00
  - data:
      entity_id: group.bore_motor_start
    service: switch.turn_on
  - service: timer.cancel
- id: '1569577490754'
  alias: Over Tank Full
  trigger:
  - entity_id: switch.over_tank_sensor
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: script.turn_off
  - data: {}
    service: timer.cancel
  - data:
      entity_id: switch.bore_stop
    service: switch.turn_on
  - data:
      entity_id: switch.motor_sump
    service: switch.turn_off
- id: '1569578047082'
  alias: If Sump has no-water at start
  trigger:
  - entity_id: switch.over_tank_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.sump_tank_status
    state: 'on'
  action:
  - data:
      entity_id: script.1569585303614
    service: script.turn_on
