- id: '1583566484464'
  alias: Turn Lights on Evening
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.gate_lamp
    service: switch.turn_on
  - data:
      entity_id: switch.elevation
    service: switch.turn_on
  - data:
      entity_id: switch.1st_flr_head_room
    service: switch.turn_on
  - data:
      entity_id: switch.1st_portico
    service: switch.turn_on
  - data:
      entity_id: switch.2nd_flr_head_room
    service: switch.turn_on
  - data:
      entity_id: switch.gnd_lamp
    service: switch.turn_on
  - data:
      entity_id: switch.vinayagar
    service: switch.turn_on
- id: '1583600836399'
  alias: Turn-off all the lights
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.gnd_lamp
    service: switch.turn_off
  - data:
      entity_id: switch.vinayagar
    service: switch.turn_off
