
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
    broker: !secret broker_ip
    port: 1883
    username: !secret broker_username
    password: !secret broker_password
    

switch light-controls:
    - platform: mqtt
      name: "ELEVATION"
      icon: mdi:light-switch
      command_topic: "cmnd/elevation_lamp/power"
      state_topic: "stat/elevation_lamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


#    - platform: mqtt
#      name: "SUMP_MOTOR"
#      icon: mdi:arch
#      command_topic: "cmnd/sumpmotor/power"
#      state_topic: "stat/sumpmotor/POWER"
#      qos: 1
#      payload_on: "ON"
#      payload_off: "OFF"
#      retain: false 
#https://community.home-assistant.io/t/mqtt-how-to-retain-sonoff-switch-setting-across-restarts-of-ha/21504

    - platform: mqtt
      name: "1st_FLR_HEAD-ROOM"
      icon: mdi:light-switch
      command_topic: "cmnd/1st_headroom/power"
      state_topic: "stat/1st_headroom/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


    - platform: mqtt
      name: "2nd_FLR_HEAD-ROOM"
      icon: mdi:light-switch
      command_topic: "cmnd/2nd_headroom/power"
      state_topic: "stat/2nd_headroom/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


    - platform: mqtt
      name: "VINAYAGAR"
      icon: mdi:light-switch
      command_topic: "cmnd/vinayagar/power"
      state_topic: "stat/vinayagar/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

      
    - platform: mqtt
      name: "GATE_LAMP"
      icon: mdi:light-switch
      command_topic: "cmnd/gatelamp/power"
      state_topic: "stat/gatelamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

      
    - platform: mqtt
      name: "GND_LAMP"
      icon: mdi:light-switch
      command_topic: "cmnd/gnd_lamp/power"
      state_topic: "stat/gnd_lamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
 
      
    - platform: mqtt
      name: "1st_PORTICO"
      icon: mdi:light-switch
      command_topic: "cmnd/1stportico/power"
      state_topic: "stat/1stportico/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


binary_sensor:
  - platform: ping
    host: !secret elevation_lamp_ip
    name: Elevation
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret sump_motor_ip
    name: Sump_Motor
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 1st_floor_head_room_ip
    name: 1st_Head_Room
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 2nd_floor_head_room_ip
    name: 2nd_Head_Room
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret vinayagar_ip
    name: Vinayagar
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret gate_lamp_ip
    name: Gate_Lamp
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret gnd_floor_lamp_ip
    name: Gnd_Lamp
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 1st_floor_portico
    name: 1st_Portico
    count: 2
    scan_interval: 30
    
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

timer:
  bore_timer:
    duration: '00:10:00'
  run_bore_timer:
    duration: '00:30:00'
  sump_timer:
    duration: '00:10:00'
      
      
