# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml

mqtt:
    broker: !secret broker_ip
    port: 1883
    username: !secret broker_username
    password: !secret broker_password

influxdb:
    host: a0d7b954-influxdb
    database: home_assistant

switch light-controls:
    - platform: mqtt
      name: "ELEVATION"
      icon: mdi:light-switch
      command_topic: "cmnd/elevation_lamp/power"
      state_topic: "stat/elevation_lamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


#    - platform: mqtt
#      name: "SUMP_MOTOR"
#      icon: mdi:arch
#      command_topic: "cmnd/sumpmotor/power"
#      state_topic: "stat/sumpmotor/POWER"
#      qos: 1
#      payload_on: "ON"
#      payload_off: "OFF"
#      retain: false 
#https://community.home-assistant.io/t/mqtt-how-to-retain-sonoff-switch-setting-across-restarts-of-ha/21504

    - platform: mqtt
      name: "1st_FLR_HEAD-ROOM"
      icon: mdi:light-switch
      command_topic: "cmnd/1st_headroom/power"
      state_topic: "stat/1st_headroom/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


    - platform: mqtt
      name: "2nd_FLR_HEAD-ROOM"
      icon: mdi:light-switch
      command_topic: "cmnd/2nd_headroom/power"
      state_topic: "stat/2nd_headroom/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"


    - platform: mqtt
      name: "VINAYAGAR"
      icon: mdi:light-switch
      command_topic: "cmnd/vinayagar/power"
      state_topic: "stat/vinayagar/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

      
    - platform: mqtt
      name: "GATE_LAMP"
      icon: mdi:light-switch
      command_topic: "cmnd/gatelamp/power"
      state_topic: "stat/gatelamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

      
    - platform: mqtt
      name: "GND_LAMP"
      icon: mdi:light-switch
      command_topic: "cmnd/gnd_lamp/power"
      state_topic: "stat/gnd_lamp/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
 
      
    - platform: mqtt
      name: "1st_PORTICO"
      icon: mdi:light-switch
      command_topic: "cmnd/1stportico/power"
      state_topic: "stat/1stportico/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

    - platform: mqtt
      name: "Tank-1"
      icon: mdi:light-switch
      command_topic: "cmnd/overtank1/power"
      state_topic: "stat/overtank1/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

    - platform: mqtt
      name: "Bore-Tanks"
      icon: mdi:light-switch
      command_topic: "cmnd/tank23/power"
      state_topic: "stat/tank23/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

    - platform: mqtt
      name: "Geek Charger"
      icon: mdi:light-switch
      command_topic: "cmnd/laptop/power"
      state_topic: "stat/laptop/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"

binary_sensor:
  - platform: ping
    host: !secret elevation_lamp_ip
    name: Elevation
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret sump_motor_ip
    name: Sump_Motor
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 1st_floor_head_room_ip
    name: 1st_Head_Room
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 2nd_floor_head_room_ip
    name: 2nd_Head_Room
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret vinayagar_ip
    name: Vinayagar
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret gate_lamp_ip
    name: Gate_Lamp
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret gnd_floor_lamp_ip
    name: Gnd_Lamp
    count: 2
    scan_interval: 30
  - platform: ping
    host: !secret 1st_floor_portico
    name: 1st_Portico
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.7
    name: MI_ROUTER
    count: 2
    scan_interval: 15
  - platform: ping
    host: !secret over_tank_1_ip
    name: Over_Tank_sensor-1
    count: 2
    scan_interval: 15
  - platform: ping
    host: !secret over_tank_23_ip
    name: Over_Tank_sensor-2
    count: 2
    scan_interval: 15
  - platform: template
    sensors:
      bore_tank_last_full_time:
        value_template: >-
            {% set last_bore_full_time = (as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.switch.bore_tanks.last_changed)) %}
            {% set last_bore_full_time_in_min = ((last_bore_full_time / 60)) | int %}
            {{ is_state("switch.bore_tanks", "off") and last_bore_full_time_in_min < 10 }}
        friendly_name: bore_fill_time 
  - platform: template
    sensors:
      corp_tank_last_full_time:
        value_template: >-
            {% set last_corp_full_time = (as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.switch.tank_1.last_changed)) %}
            {% set last_corp_full_time_in_min = ((last_corp_full_time / 60)) | int %}
            {{ is_state("switch.tank_1", "off") and last_corp_full_time_in_min < 10 }}
        friendly_name: corp_fill_time    
    
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
  - platform: time_date
  
#  - platform: template
#    sensors:
#       second_floor_avg_rtt:
#          value_template: "{{ state_attr('binary_sensor.2nd_Head_Room','round_trip_time_avg') | int }}"
#          friendly_name: 'Floor_RTT'



#Ubuntu charge
  - platform: command_line
    name: Geek Laptop Battery
    command: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no geek@192.168.1.245 cat /sys/class/power_supply/BAT0/capacity"
    unit_of_measurement: "%"
    scan_interval: 31536000

webostv:
  host: 192.168.1.214
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: E8-F2-E2-60-B6-D4
  customize:
    sources:
      - AVhhgggg
      - youtube
      - netflix
      - livetv
media_player:


notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

  - name: rednotify
    platform: group
    services:
      - service: living_room_tv
        data:
            data:
                icon: www/red.png

  - name: yellownotify
    platform: group
    services:
      - service: living_room_tv
        data:
            data:
                icon: www/yellow.png

  - name: bluenotify
    platform: group
    services:
      - service: living_room_tv
        data:
            data:
                icon: www/blue.png

  - name: greennotify
    platform: group
    services:
      - service: living_room_tv
        data:
            data:
                icon: www/green.png
    
alert:
  bore_tank_empty:
    name: Bore Tank Going to be Empty
    message: '{{ as_timestamp(states.switch.bore_tanks.last_changed) | timestamp_local }} Tank going to be Empty, On the Bore motor'
    #done_message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Tank will be Full, Off the Bore motor'
    entity_id: switch.bore_tanks
    state: 'on'
    repeat: 0.1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - rednotify
  corp_tank_empty:
    name: Corp Tank Going to be Empty
    message: '{{ as_timestamp(states.switch.tank_1.last_changed) | timestamp_local }} Corp Tank will be Empty, On the Sump motor'
    #done_message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Corp Tank will be Full, Off the Sump motor'
    entity_id: switch.tank_1
    state: 'on'
    repeat: 0.1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - bluenotify

  bore_tank_full_alert:
    name: Bore Tank Filled
    message: '{{ as_timestamp(states.switch.bore_tanks.last_changed) | timestamp_local }} BORE Tank About to Full, OFF the Bore motor'
    #done_message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Tank will be Full, Off the Bore motor'
    entity_id: binary_sensor.bore_tank_last_full_time
    repeat: 0.1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - greennotify
      
  corp_tank_full_alert:
    name: Corp Tank Filled
    message: '{{ as_timestamp(states.switch.tank_1.last_changed) | timestamp_local }} CORP Tank About to Full, OFF the Bore motor'
    #done_message: '{{now().strftime("%b %d, %Y %I:%M%p")}} Tank will be Full, Off the Bore motor'
    entity_id: binary_sensor.corp_tank_last_full_time
    repeat: 0.1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - greennotify


#timer:
#  bore_timer:
#    duration: '00:10:00'
#  run_bore_timer:
#    duration: '00:30:00'
#  sump_timer:
#    duration: '00:10:00'